world: world
x: 0.5
y: -2.0
z: 0.5
yaw: 0.0
pitch: 0.0
joinspawn: true
firstonly: true
respawn: true
worldsetspawn: true
respawntobed: true
bedteleported: true
spawned: true
spawncost: 0.0
bedcost: 0.0
homecost: 0.0
sethomecost: 0.0
home: true
homemax: 0