name: HubSpawn
main: org.densyakun.bukkit.hubspawn.Main
version: 1.7
author: Densyakun.
website: http://densyakuncreate.wiki.fc2.com/
commands:
   spawn:
   hub:
   setspawn:
   bed:
   home:
   sethome:
   homelist:
   removehome:
